/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.identity.moesif.publisher.http;

/**
 * Constants for the Moesif HTTP output event adapter.
 *
 * <p>The adapter / dynamic property names intentionally keep the {@code http.*} prefix used by the generic
 * HTTP output adapter so the publisher XMLs generated by the Moesif configuration module
 * (see {@code MoesifPublisherUtils}) keep working unchanged.
 */
public class MoesifHTTPEventAdapterConstants {

    public static final String ADAPTER_TYPE_MOESIF_HTTP = "moesif-http";

    // Dynamic adapter properties.
    public static final String ADAPTER_MESSAGE_URL = "http.url";
    public static final String ADAPTER_HEADERS = "http.headers";

    // Static adapter properties.
    public static final String ADAPTER_AUTH_TYPE = "http.authType";
    public static final String ADAPTER_API_KEY_HEADER = "http.apiKeyHeader";
    public static final String ADAPTER_API_KEY_VALUE = "http.apiKeyValue";
    public static final String ADAPTER_SECRET_PROVIDER = "http.secret.provider";
    public static final String ADAPTER_HTTP_CLIENT_METHOD = "http.client.method";
    public static final String ADAPTER_PROXY_HOST = "http.proxy.host";
    public static final String ADAPTER_PROXY_PORT = "http.proxy.port";

    // HTTP client methods.
    public static final String CONSTANT_HTTP_POST = "HttpPost";
    public static final String CONSTANT_HTTP_PUT = "HttpPut";
    public static final String CONSTANT_HTTP_GET = "HttpGet";

    // Supported authentication types.
    public static final String AUTH_TYPE_API_KEY = "API_KEY";
    public static final String AUTH_TYPE_NONE = "NONE";

    /**
     * Property name under which the API key is stored in the secret store
     * (see {@code EventAdapterSecretProcessor}).
     */
    public static final String SECRET_PROPERTY_API_KEY_VALUE = "apiKeyValue";

    /**
     * Default secret provider identifier. Matches the provider the Moesif configuration module registers
     * collector keys under ({@code MoesifConfigurationConstants.MOESIF_SECRET_PROVIDER}).
     */
    public static final String DEFAULT_SECRET_PROVIDER = "MOESIF_SECRET_PROVIDER";

    // Global properties (output-event-adapters.xml) controlling the shared executor / connection pool.
    public static final String ADAPTER_MIN_THREAD_POOL_SIZE_NAME = "minThread";
    public static final String ADAPTER_MAX_THREAD_POOL_SIZE_NAME = "maxThread";
    public static final String ADAPTER_KEEP_ALIVE_TIME_NAME = "keepAliveTimeInMillis";
    public static final String ADAPTER_EXECUTOR_JOB_QUEUE_SIZE_NAME = "jobQueueSize";
    public static final String DEFAULT_MAX_CONNECTIONS_PER_HOST_NAME = "defaultMaxConnectionsPerHost";
    public static final String MAX_TOTAL_CONNECTIONS_NAME = "maxTotalConnections";

    public static final int ADAPTER_MIN_THREAD_POOL_SIZE = 8;
    public static final int ADAPTER_MAX_THREAD_POOL_SIZE = 100;
    public static final int ADAPTER_EXECUTOR_JOB_QUEUE_SIZE = 2000;
    public static final long DEFAULT_KEEP_ALIVE_TIME_IN_MILLIS = 20000;
    public static final int DEFAULT_MAX_CONNECTIONS_PER_HOST = 2;
    public static final int DEFAULT_MAX_TOTAL_CONNECTIONS = 20;

    // Header string parsing ("Name:Value,Name:Value").
    public static final String HEADER_SEPARATOR = ",";
    public static final String ENTRY_SEPARATOR = ":";

    public static final String CONTENT_TYPE_JSON = "application/json";

    private MoesifHTTPEventAdapterConstants() {

    }
}
